### ISSUE TITLE
Failed to start the minecraft server

### ISSUE THREAD

**Issue by CryptNation** [BlakeBr0/MysticalAgradditions#77]
java.lang.NullPointerExceptionRegistry Object not present: mysticalagradditions:molten_inferium
[23.11 17:01:20] [Server] 	at java.util.Objects.requireNonNull(Objects.java:290) ~[?:1.8.0_{}
[23.11 17:01:20] [Server] 	at net.minecraftforge.fml.RegistryObject.get(RegistryObject.java:120) ~[forge:?] {re:mixin,re:classloading}
[23.11 17:01:20] [Server] 	at net.minecraftforge.fml.RegistryObject.get(RegistryObject.java:39) ~[forge:?] {re:mixin,re:classloading}
[23.11 17:01:20] [Server] 	at net.minecraft.block.FlowingFluidBlock.getFluid(FlowingFluidBlock.java:175) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:fml:forge:flowingfluidblock,pl:runtimedistcleaner:A}
[23.11 17:01:20] [Server] 	at net.minecraft.block.FlowingFluidBlock.func_220071_b(FlowingFluidBlock.java:65) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:fml:forge:flowingfluidblock,pl:runtimedistcleaner:A}
[23.11 17:01:20] [Server] 	at net.minecraft.block.AbstractBlock$AbstractBlockState$Cache.<init>(AbstractBlock.java:765) ~[?:?] {re:classloading}
[23.11 17:01:20] [Server] 	at net.minecraft.block.AbstractBlock$AbstractBlockState$Cache.<init>(AbstractBlock.java:736) ~[?:?] {re:classloading}
[23.11 17:01:20] [Server] 	at net.minecraft.block.AbstractBlock$AbstractBlockState.func_215692_c(AbstractBlock.java:397) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:libx.mixins.json:MixinAbstractBlockState,pl:mixin:APP:immersiveengineering.mixins.json:coremods.AbstractBlockStateMixin,pl:mixin:A,pl:runtimedistcleaner:A}
[23.11 17:01:20] [Server] 	at net.minecraftforge.registries.GameData$BlockCallbacks.onBake(GameData.java:519) ~[forge:?] {re:classloading}
[23.11 17:01:20] [Server] 	at net.minecraftforge.registries.ForgeRegistry.bake(ForgeRegistry.java:525) ~[forge:?] {re:classloading}
[23.11 17:01:20] [Server] 	at net.minecraftforge.registries.GameData.lambda$freezeData$5(GameData.java:303) ~[forge:?] {re:classloading}
[23.11 17:01:20] [Server] 	at com.google.common.collect.HashBiMap.forEach(HashBiMap.java:528) ~[server-1.16.5-20210115.111550-extra.jar:?] {}
[23.11 17:01:20] [Server] 	at net.minecraftforge.registries.GameData.freezeData(GameData.java:301) ~[forge:?] {re:classloading}
[23.11 17:01:20] [Server] 	at net.minecraftforge.fml.ModLoader.finishMods(ModLoader.java:226) ~[forge:?] {re:classloading}
[23.11 17:01:20] [Server] 	at net.minecraftforge.fml.server.ServerModLoader.load(ServerModLoader.java:46) ~[forge:?] {re:classloading}
[23.11 17:01:20] [Server] 	at net.minecraft.server.Main.main(Main.java:95) ~[?:?] {re:classloading}
[23.11 17:01:20] [Server] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_{}
[23.11 17:01:20] [Server] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_{}
[23.11 17:01:20] [Server] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_{}
[23.11 17:01:20] [Server] 	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_{}
[23.11 17:01:20] [Server] 	at net.minecraftforge.fml.loading.FMLServerLaunchProvider.lambda$launchService$0(FMLServerLaunchProvider.java:51) ~[custom.jar:36.{}
[23.11 17:01:20] [Server] 	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.9.jar:?] {}
[23.11 17:01:20] [Server] 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.9.jar:?] {}
[23.11 17:01:20] [Server] 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.9.jar:?] {}
[23.11 17:01:20] [Server] 	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.9.jar:?] {}
[23.11 17:01:20] [Server] 	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.9.jar:?] {}
[23.11 17:01:20] [Server] 	at net.minecraftforge.server.ServerMain$Runner.runLauncher(ServerMain.java:63) [custom.jar:?] {}
[23.11 17:01:20] [Server] 	at net.minecraftforge.server.ServerMain$Runner.access$100(ServerMain.java:60) [custom.jar:?] {}
[23.11 17:01:20] [Server] 	at net.minecraftforge.server.ServerMain.main(ServerMain.java:57) [custom.jar:?] {}

This error keeps crashing my server when it restarts.
Is there any solution to this?

**Comment by BlakeBr0** [comment]
Is this the only error in the log?

**Comment by CryptNation** [comment]
Hey!
This appears to be the only error relevent to the crash,
However, I will upload it here for you if you want to have a look.

[Debug.log Download](https://www.dropbox.com/s/wwkwugzk0ahgye7/debug-2.log.gz?dl=0)
