### ISSUE TITLE
Tinkers' Invalid Modifier

### ISSUE THREAD

**Issue by ZeroInputCtrl** [BlakeBr0/MysticalAgradditions#88]
I "think" this bug report belongs here, if not which mod is responsible for it?
**Describe the bug**
Tinker's tools have an invalid modifier shown in the books and in JEI

**Expected behavior**
Modifiers should be valid

**Screenshots / Scripts / Logs**
<img src="https://monosnap.com/image/9Z1P2iWWfeQnmG6BKqZWAqFB2p1RbS"/>

**Versions (please complete the following information):**
 - Minecraft: 1.18.2 - ATM7 Pack
 - Forge: 4.1.20
 - Cucumber: 5.1.0
 - Mystical Agriculture: 5.1.0
 - Mystical Agradditions: 5.1.1

**Comment by border999** [comment]
same issue here

**Comment by itsdinkd** [comment]
```java
[17:51:15] [main/ERROR] [ne.mi.re.ObjectHolderRegistry/]:
java.lang.RuntimeException: Failed to apply some object holders, see suppressed exceptions for details
        at net.minecraftforge.registries.ObjectHolderRegistry.applyObjectHolders(ObjectHolderRegistry.java:174) ~[forge-1.18.2-40.1.48-universal.jar%23345!/:?] {re:classloading}
        at net.minecraftforge.registries.GameData.applyHolderLookups(GameData.java:384) ~[forge-1.18.2-40.1.48-universal.jar%23345!/:?] {re:mixin,re:classloading,pl:mixin:APP:flytre_lib-forge.mixins.json:loader.GameDataMixin,pl:mixin:A}
        at net.minecraftforge.registries.GameData.lambda$postRegistryEventDispatch$19(GameData.java:377) ~[forge-1.18.2-40.1.48-universal.jar%23345!/:?] {re:mixin,re:classloading,pl:mixin:APP:flytre_lib-forge.mixins.json:loader.GameDataMixin,pl:mixin:A}
        at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
        at net.minecraftforge.fml.ModWorkManager$SyncExecutor.driveOne(ModWorkManager.java:42) ~[fmlcore-1.18.2-40.1.48.jar%23341!/:?] {}
        at net.minecraftforge.fml.ModWorkManager$DrivenExecutor.drive(ModWorkManager.java:26) ~[fmlcore-1.18.2-40.1.48.jar%23341!/:?] {}
        at net.minecraftforge.fml.ModLoader.waitForTransition(ModLoader.java:201) ~[fmlcore-1.18.2-40.1.48.jar%23341!/:?] {}
        at net.minecraftforge.fml.ModLoader.lambda$dispatchAndHandleError$21(ModLoader.java:186) ~[fmlcore-1.18.2-40.1.48.jar%23341!/:?] {}
        at java.util.Optional.ifPresent(Optional.java:178) ~[?:?] {re:mixin}
        at net.minecraftforge.fml.ModLoader.dispatchAndHandleError(ModLoader.java:186) ~[fmlcore-1.18.2-40.1.48.jar%23341!/:?] {}
        at net.minecraftforge.fml.ModLoader.lambda$gatherAndInitializeMods$11(ModLoader.java:163) ~[fmlcore-1.18.2-40.1.48.jar%23341!/:?] {}
        at java.lang.Iterable.forEach(Iterable.java:75) ~[?:?] {re:mixin}
        at net.minecraftforge.fml.ModLoader.gatherAndInitializeMods(ModLoader.java:163) ~[fmlcore-1.18.2-40.1.48.jar%23341!/:?] {}
        at net.minecraftforge.server.loading.ServerModLoader.load(ServerModLoader.java:32) ~[forge-1.18.2-40.1.48-universal.jar%23345!/:?] {re:classloading}
        at net.minecraft.server.Main.main(Main.java:112) ~[server-1.18.2-20220404.173914-srg.jar%23340!/:?] {re:classloading,re:mixin,pl:mixin:A}
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
        at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
        at net.minecraftforge.fml.loading.targets.CommonServerLaunchHandler.lambda$launchService$0(CommonServerLaunchHandler.java:32) ~[fmlloader-1.18.2-40.1.48.jar%2316!/:?] {}
        at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-9.1.3.jar%235!/:?] {}
        at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-9.1.3.jar%235!/:?] {}
        at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-9.1.3.jar%235!/:?] {}
        at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-9.1.3.jar%235!/:?] {}
        at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-9.1.3.jar%235!/:?] {}
        at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-9.1.3.jar%235!/:?] {}
        at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-9.1.3.jar%235!/:?] {}
        at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:149) [bootstraplauncher-1.0.0.jar:?] {}
        Suppressed: java.lang.IllegalStateException: Unable to find registry for type slimeknights.tconstruct.library.modifiers.Modifier for mod "mysticalagradditions". Check the 'caused by' to see further stack.
                at net.minecraftforge.registries.RegistryObject$1.accept(RegistryObject.java:258) ~[forge-1.18.2-40.1.48-universal.jar%23345!/:?] {re:classloading}
                at net.minecraftforge.registries.RegistryObject$1.accept(RegistryObject.java:243) ~[forge-1.18.2-40.1.48-universal.jar%23345!/:?] {re:classloading}
                at net.minecraftforge.registries.ObjectHolderRegistry.lambda$applyObjectHolders$10(ObjectHolderRegistry.java:178) ~[forge-1.18.2-40.1.48-universal.jar%23345!/:?] {re:classloading}
                at java.lang.Iterable.forEach(Iterable.java:75) ~[?:?] {re:mixin}
                at net.minecraftforge.registries.ObjectHolderRegistry.applyObjectHolders(ObjectHolderRegistry.java:175) ~[forge-1.18.2-40.1.48-universal.jar%23345!/:?] {re:classloading}
                at net.minecraftforge.registries.GameData.applyHolderLookups(GameData.java:384) ~[forge-1.18.2-40.1.48-universal.jar%23345!/:?] {re:mixin,re:classloading,pl:mixin:APP:flytre_lib-forge.mixins.json:loader.GameDataMixin,pl:mixin:A}
                at net.minecraftforge.registries.GameData.lambda$postRegistryEventDispatch$19(GameData.java:377) ~[forge-1.18.2-40.1.48-universal.jar%23345!/:?] {re:mixin,re:classloading,pl:mixin:APP:flytre_lib-forge.mixins.json:loader.GameDataMixin,pl:mixin:A}
                at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
                at net.minecraftforge.fml.ModWorkManager$SyncExecutor.driveOne(ModWorkManager.java:42) ~[fmlcore-1.18.2-40.1.48.jar%23341!/:?] {}
                at net.minecraftforge.fml.ModWorkManager$DrivenExecutor.drive(ModWorkManager.java:26) ~[fmlcore-1.18.2-40.1.48.jar%23341!/:?] {}
                at net.minecraftforge.fml.ModLoader.waitForTransition(ModLoader.java:201) ~[fmlcore-1.18.2-40.1.48.jar%23341!/:?] {}
                at net.minecraftforge.fml.ModLoader.lambda$dispatchAndHandleError$21(ModLoader.java:186) ~[fmlcore-1.18.2-40.1.48.jar%23341!/:?] {}
                at java.util.Optional.ifPresent(Optional.java:178) ~[?:?] {re:mixin}
                at net.minecraftforge.fml.ModLoader.dispatchAndHandleError(ModLoader.java:186) ~[fmlcore-1.18.2-40.1.48.jar%23341!/:?] {}
                at net.minecraftforge.fml.ModLoader.lambda$gatherAndInitializeMods$11(ModLoader.java:163) ~[fmlcore-1.18.2-40.1.48.jar%23341!/:?] {}
                at java.lang.Iterable.forEach(Iterable.java:75) ~[?:?] {re:mixin}
                at net.minecraftforge.fml.ModLoader.gatherAndInitializeMods(ModLoader.java:163) ~[fmlcore-1.18.2-40.1.48.jar%23341!/:?] {}
                at net.minecraftforge.server.loading.ServerModLoader.load(ServerModLoader.java:32) ~[forge-1.18.2-40.1.48-universal.jar%23345!/:?] {re:classloading}
                at net.minecraft.server.Main.main(Main.java:112) ~[server-1.18.2-20220404.173914-srg.jar%23340!/:?] {re:classloading,re:mixin,pl:mixin:A}
                at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
                at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
                at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
                at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
                at net.minecraftforge.fml.loading.targets.CommonServerLaunchHandler.lambda$launchService$0(CommonServerLaunchHandler.java:32) ~[fmlloader-1.18.2-40.1.48.jar%2316!/:?] {}
                at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-9.1.3.jar%235!/:?] {}
                at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-9.1.3.jar%235!/:?] {}
                at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-9.1.3.jar%235!/:?] {}
                at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-9.1.3.jar%235!/:?] {}
                at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-9.1.3.jar%235!/:?] {}
                at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-9.1.3.jar%235!/:?] {}
                at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-9.1.3.jar%235!/:?] {}
                at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:149) [bootstraplauncher-1.0.0.jar:?] {}
        Caused by: java.lang.Throwable: Calling Site from mod: mysticalagradditions
                at net.minecraftforge.registries.RegistryObject.<init>(RegistryObject.java:241) ~[forge-1.18.2-40.1.48-universal.jar%23345!/:?] {re:mixin,xf:fml:forge:registry_object_binary_compat,re:classloading,xf:fml:forge:registry_object_binary_compat}
                at net.minecraftforge.registries.RegistryObject.of(RegistryObject.java:77) ~[forge-1.18.2-40.1.48-universal.jar%23345!/:?] {re:mixin,xf:fml:forge:registry_object_binary_compat,re:classloading,xf:fml:forge:registry_object_binary_compat}
                at net.minecraftforge.registries.DeferredRegister.register(DeferredRegister.java:209) ~[forge-1.18.2-40.1.48-universal.jar%23345!/:?] {re:classloading}
                at com.blakebr0.mysticalagradditions.compat.tconstruct.ModModifiers.<clinit>(ModModifiers.java:13) ~[MysticalAgradditions-1.18.2-5.1.1.jar%23224!/:5.1.1] {re:classloading}
                at com.blakebr0.mysticalagradditions.MysticalAgradditions.<init>(MysticalAgradditions.java:45) ~[MysticalAgradditions-1.18.2-5.1.1.jar%23224!/:5.1.1] {re:classloading}
                at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?] {}
                at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?] {}
                at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?] {}
                at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?] {}
                at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?] {}
                at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:67) ~[javafmllanguage-1.18.2-40.1.48.jar%23342!/:?] {}
                at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:106) ~[fmlcore-1.18.2-40.1.48.jar%23341!/:?] {}
                at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
                at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?] {}
                at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
                at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
                at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {re:computing_frames}
                at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {re:computing_frames}
                at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {}
        Suppressed: java.lang.IllegalStateException: Unable to find registry for type slimeknights.tconstruct.library.modifiers.Modifier for mod "mysticalagradditions". Check the 'caused by' to see further stack.
                at net.minecraftforge.registries.RegistryObject$1.accept(RegistryObject.java:258) ~[forge-1.18.2-40.1.48-universal.jar%23345!/:?] {re:classloading}
                at net.minecraftforge.registries.RegistryObject$1.accept(RegistryObject.java:243) ~[forge-1.18.2-40.1.48-universal.jar%23345!/:?] {re:classloading}
                at net.minecraftforge.registries.ObjectHolderRegistry.lambda$applyObjectHolders$10(ObjectHolderRegistry.java:178) ~[forge-1.18.2-40.1.48-universal.jar%23345!/:?] {re:classloading}
                at java.lang.Iterable.forEach(Iterable.java:75) ~[?:?] {re:mixin}
                at net.minecraftforge.registries.ObjectHolderRegistry.applyObjectHolders(ObjectHolderRegistry.java:175) ~[forge-1.18.2-40.1.48-universal.jar%23345!/:?] {re:classloading}
                at net.minecraftforge.registries.GameData.applyHolderLookups(GameData.java:384) ~[forge-1.18.2-40.1.48-universal.jar%23345!/:?] {re:mixin,re:classloading,pl:mixin:APP:flytre_lib-forge.mixins.json:loader.GameDataMixin,pl:mixin:A}
                at net.minecraftforge.registries.GameData.lambda$postRegistryEventDispatch$19(GameData.java:377) ~[forge-1.18.2-40.1.48-universal.jar%23345!/:?] {re:mixin,re:classloading,pl:mixin:APP:flytre_lib-forge.mixins.json:loader.GameDataMixin,pl:mixin:A}
                at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
                at net.minecraftforge.fml.ModWorkManager$SyncExecutor.driveOne(ModWorkManager.java:42) ~[fmlcore-1.18.2-40.1.48.jar%23341!/:?] {}
                at net.minecraftforge.fml.ModWorkManager$DrivenExecutor.drive(ModWorkManager.java:26) ~[fmlcore-1.18.2-40.1.48.jar%23341!/:?] {}
                at net.minecraftforge.fml.ModLoader.waitForTransition(ModLoader.java:201) ~[fmlcore-1.18.2-40.1.48.jar%23341!/:?] {}
                at net.minecraftforge.fml.ModLoader.lambda$dispatchAndHandleError$21(ModLoader.java:186) ~[fmlcore-1.18.2-40.1.48.jar%23341!/:?] {}
                at java.util.Optional.ifPresent(Optional.java:178) ~[?:?] {re:mixin}
                at net.minecraftforge.fml.ModLoader.dispatchAndHandleError(ModLoader.java:186) ~[fmlcore-1.18.2-40.1.48.jar%23341!/:?] {}
                at net.minecraftforge.fml.ModLoader.lambda$gatherAndInitializeMods$11(ModLoader.java:163) ~[fmlcore-1.18.2-40.1.48.jar%23341!/:?] {}
                at java.lang.Iterable.forEach(Iterable.java:75) ~[?:?] {re:mixin}
                at net.minecraftforge.fml.ModLoader.gatherAndInitializeMods(ModLoader.java:163) ~[fmlcore-1.18.2-40.1.48.jar%23341!/:?] {}
                at net.minecraftforge.server.loading.ServerModLoader.load(ServerModLoader.java:32) ~[forge-1.18.2-40.1.48-universal.jar%23345!/:?] {re:classloading}
                at net.minecraft.server.Main.main(Main.java:112) ~[server-1.18.2-20220404.173914-srg.jar%23340!/:?] {re:classloading,re:mixin,pl:mixin:A}
                at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
                at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
                at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
                at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
                at net.minecraftforge.fml.loading.targets.CommonServerLaunchHandler.lambda$launchService$0(CommonServerLaunchHandler.java:32) ~[fmlloader-1.18.2-40.1.48.jar%2316!/:?] {}
                at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-9.1.3.jar%235!/:?] {}
                at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-9.1.3.jar%235!/:?] {}
                at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-9.1.3.jar%235!/:?] {}
                at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-9.1.3.jar%235!/:?] {}
                at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-9.1.3.jar%235!/:?] {}
                at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-9.1.3.jar%235!/:?] {}
                at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-9.1.3.jar%235!/:?] {}
                at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:149) [bootstraplauncher-1.0.0.jar:?] {}
        Caused by: java.lang.Throwable: Calling Site from mod: mysticalagradditions
                at net.minecraftforge.registries.RegistryObject.<init>(RegistryObject.java:241) ~[forge-1.18.2-40.1.48-universal.jar%23345!/:?] {re:mixin,xf:fml:forge:registry_object_binary_compat,re:classloading,xf:fml:forge:registry_object_binary_compat}
                at net.minecraftforge.registries.RegistryObject.of(RegistryObject.java:77) ~[forge-1.18.2-40.1.48-universal.jar%23345!/:?] {re:mixin,xf:fml:forge:registry_object_binary_compat,re:classloading,xf:fml:forge:registry_object_binary_compat}
                at net.minecraftforge.registries.DeferredRegister.register(DeferredRegister.java:209) ~[forge-1.18.2-40.1.48-universal.jar%23345!/:?] {re:classloading}
                at com.blakebr0.mysticalagradditions.compat.tconstruct.ModModifiers.<clinit>(ModModifiers.java:14) ~[MysticalAgradditions-1.18.2-5.1.1.jar%23224!/:5.1.1] {re:classloading}
                at com.blakebr0.mysticalagradditions.MysticalAgradditions.<init>(MysticalAgradditions.java:45) ~[MysticalAgradditions-1.18.2-5.1.1.jar%23224!/:5.1.1] {re:classloading}
                at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?] {}
                at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?] {}
                at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?] {}
                at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?] {}
                at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?] {}
                at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:67) ~[javafmllanguage-1.18.2-40.1.48.jar%23342!/:?] {}
                at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:106) ~[fmlcore-1.18.2-40.1.48.jar%23341!/:?] {}
                at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
                at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?] {}
                at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
                at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
                at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {re:computing_frames}
                at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {re:computing_frames}
                at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {}
                ```

**Comment by MCBEModder2020** [comment]
same in floof 6 pack
with tinkers TConstruct-1.18.2-3.5.1.31.jar

**Comment by pavog** [comment]
Some more info:
I installed Tinkers Construct and Mystical Agradditions on a fresh new Forge 1.18.2 server. 

- Forge 1.18.2 (40.1.54)
- [Tinkers' Construct 3.5.1.31 for 1.18.2](https://www.curseforge.com/minecraft/mc-mods/tinkers-construct/files/3829979)
- [Mantle 1.9.27 for 1.18.2](https://www.curseforge.com/minecraft/mc-mods/mantle/files/3829975)
- [MysticalAgradditions-1.18.2-5.1.1.jar](https://www.curseforge.com/minecraft/mc-mods/mystical-agradditions/files/3741099)
- [Cucumber-1.18.2-5.1.1.jar](https://www.curseforge.com/minecraft/mc-mods/cucumber/files/3804158)
- [MysticalAgriculture-1.18.2-5.1.0.jar](https://www.curseforge.com/minecraft/mc-mods/mystical-agriculture/files/3686412)

`Suppressed: java.lang.IllegalStateException: Unable to find registry for type slimeknights.tconstruct.library.modifiers.Modifier for mod "mysticalagradditions". Check the 'caused by' to see further stack.`
...
`Caused by: java.lang.Throwable: Calling Site from mod: mysticalagradditions`

Full log: https://mclo.gs/qYUeDd7
